# 配置文件

# 功能：给女朋友发早安和土味情话
loveMsg:
  # 与女朋友相识的日子
  start_stamp: 2015-06-17
  # 女朋友所在城市（不要带‘市’）
  city_name: 北京
  # 对女朋友的爱称
  girl_name: 汪女士
  # 对自己的称呼
  boy_name: 喵先生
  # 点击卡片详情地址
  card_url: https://chenxiao.wang
  # 天气生活指数提示（默认开启）
  weather_tips: true
  # 极端天气温度提醒（默认开启）
  # 卡片内容字节限制可能显示不完全
  weather_tem: true
  # 农历信息（默认开启）
  date_lunarInfo: true
  # 土味情话
  say_love: true
  # 彩虹屁
  cai_hong_pi: true
  # 一言
  one_word: false
  # 最美宋词
  song_lyrics: false # true
  # one杂志
  one_magazines: false
  # 网易云热评
  net_ease_cloud: false
  # 每日英语
  day_english: false

  # 生日倒计时
  birthday_down:
    - {date: 10-17, info: 暖宝生日, info2: 祝暖宝生日快乐}
    - {date: 01-21, info: 喵先生生日, info2: 祝喵先生生日快乐}
    - {date: 09-27, info: 汪女士生日, info2: 祝汪女士生日快乐}
    - {date: 08-30, info: 沫沫生日, info2: 祝沫沫生日快乐}
 